###
## group/default.yaml
###

default_view:
  name: HOME
  view: true
  control: hidden
  icon: mdi:home
  entities:
    - weather.home
    - group.info
    - group.motion_cameras
    - group.motion_annotated_details
    - group.motion_annotated_history_graphs

motion_cameras:
  name: Motion Cameras
  view: false
  control: hidden
  entities:
    - camera.motion_event_end
    - camera.motion_event_annotated
    - camera.motion_event_animated

info:
  name: Info
  view: false
  control: hidden
  entities:
    - sensor.date
    - sensor.time
    - sensor.host_lan_ip
    - sensor.host_wan_ip
    - sun.sun
